"""added cart table

Revision ID: 46062dea79c7
Revises: 318488fef3bb
Create Date: 2023-12-16 03:21:38.757169

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from app.model.cart_model import ProductItem


# revision identifiers, used by Alembic.
revision = '46062dea79c7'
down_revision = '318488fef3bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('products', sqlmodel.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
